workflows: #Defined set of rules for defining a collection of jobs and their run order
  version: 2
  test-build-deploy:
    jobs:
      - npm
      - test:
          requires:
            - npm 
      - deploy-dev:
          requires:
            - test #One follows the other?
          filters:
            branches:
              only: develop

#github requires both 'build-and-test' and 'build' run before approving pull requests
jobs:
  deploy-dev:
    working_directory: ~/circleCITut # name of root directory where steps will run
    docker: #steps to run with Docker
      - image: circleci/node:9.9.0 # This image as the primary container; this is where all `steps` will run
      # - image: mongo:4.2.0 # and this image is the secondary service container
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleCITut
      - run: npm install
      - run: 
          name: Run tests
          command: npm test
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a circlecitest web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a circlecitest web
